export const opiskelijat = [
  { id: 1, opiskelijanumero: "1001", etunimi: "Matti", sukunimi: "Meikäläinen", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 2, opiskelijanumero: "1002", etunimi: "Liisa", sukunimi: "Virtanen", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 3, opiskelijanumero: "1003", etunimi: "Eero", sukunimi: "Lahti", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 4, opiskelijanumero: "1004", etunimi: "Sanna", sukunimi: "Korhonen", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 5, opiskelijanumero: "1005", etunimi: "Antti", sukunimi: "Nieminen", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 6, opiskelijanumero: "1006", etunimi: "Kaisa", sukunimi: "Laakso", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 7, opiskelijanumero: "1007", etunimi: "Jukka", sukunimi: "Heikkinen", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 8, opiskelijanumero: "1008", etunimi: "Maria", sukunimi: "Salonen", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 9, opiskelijanumero: "1009", etunimi: "Timo", sukunimi: "Kallio", vuosikurssiId: 1, rooli: "opiskelija" },
  { id: 10, opiskelijanumero: "1010", etunimi: "Elina", sukunimi: "Mäkinen", vuosikurssiId: 1, rooli: "opiskelija" },

  { id: 11, opiskelijanumero: "2001", etunimi: "Eero", sukunimi: "Lahti", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 12, opiskelijanumero: "2002", etunimi: "Hanna", sukunimi: "Räsänen", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 13, opiskelijanumero: "2003", etunimi: "Jari", sukunimi: "Peltonen", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 14, opiskelijanumero: "2004", etunimi: "Laura", sukunimi: "Virtanen", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 15, opiskelijanumero: "2005", etunimi: "Mikko", sukunimi: "Hämäläinen", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 16, opiskelijanumero: "2006", etunimi: "Sari", sukunimi: "Koski", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 17, opiskelijanumero: "2007", etunimi: "Petri", sukunimi: "Niemi", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 18, opiskelijanumero: "2008", etunimi: "Anu", sukunimi: "Lehtonen", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 19, opiskelijanumero: "2009", etunimi: "Janne", sukunimi: "Salmi", vuosikurssiId: 2, rooli: "opiskelija" },
  { id: 20, opiskelijanumero: "2010", etunimi: "Tiina", sukunimi: "Koskinen", vuosikurssiId: 2, rooli: "opiskelija" },
];