export const opiskelijat = [
  { id: 1, vuosikurssiId: 1, ryhmaId: 1, opiskelijanumero: "1001", etunimi: "Matti", sukunimi: "Meikäläinen",  rooli: "opiskelija"},
  { id: 2, vuosikurssiId: 1, ryhmaId: 1, opiskelijanumero: "1002", etunimi: "Liisa", sukunimi: "Virtanen", rooli: "opiskelija" },
  { id: 3, vuosikurssiId: 1, ryhmaId: 1, opiskelijanumero: "1003", etunimi: "Eero", sukunimi: "Lahti", rooli: "opiskelija" },
  { id: 4, vuosikurssiId: 1, ryhmaId: 2, opiskelijanumero: "1004", etunimi: "Sanna", sukunimi: "Korhonen", rooli: "opiskelija" },
  { id: 5, vuosikurssiId: 1, ryhmaId: 2, opiskelijanumero: "1005", etunimi: "Antti", sukunimi: "Nieminen", rooli: "opiskelija" },
  { id: 6, vuosikurssiId: 1, ryhmaId: 2, opiskelijanumero: "1006", etunimi: "Kaisa", sukunimi: "Laakso", rooli: "opiskelija" },
  { id: 7, vuosikurssiId: 1, ryhmaId: 3, opiskelijanumero: "1007", etunimi: "Jukka", sukunimi: "Heikkinen", rooli: "opiskelija" },
  { id: 8, vuosikurssiId: 1, ryhmaId: 3, opiskelijanumero: "1008", etunimi: "Maria", sukunimi: "Salonen", rooli: "opiskelija" },
  { id: 9, vuosikurssiId: 1, ryhmaId: 3, opiskelijanumero: "1009", etunimi: "Timo", sukunimi: "Kallio", rooli: "opiskelija" },
  { id: 10, vuosikurssiId: 1, ryhmaId: 1, opiskelijanumero: "1010", etunimi: "Elina", sukunimi: "Mäkinen", rooli: "opiskelija" },

  { id: 11, vuosikurssiId: 2, ryhmaId: 1, opiskelijanumero: "2001", etunimi: "Eero", sukunimi: "Lahti", rooli: "opiskelija" },
  { id: 12, vuosikurssiId: 2, ryhmaId: 1, opiskelijanumero: "2002", etunimi: "Hanna", sukunimi: "Räsänen", rooli: "opiskelija" },
  { id: 13, vuosikurssiId: 2, ryhmaId: 2, opiskelijanumero: "2003", etunimi: "Jari", sukunimi: "Peltonen", rooli: "opiskelija" },
  { id: 14, vuosikurssiId: 2, ryhmaId: 2, opiskelijanumero: "2004", etunimi: "Laura", sukunimi: "Virtanen", rooli: "opiskelija" },
  { id: 15, vuosikurssiId: 2, ryhmaId: 2, opiskelijanumero: "2005", etunimi: "Mikko", sukunimi: "Hämäläinen", rooli: "opiskelija" },
  { id: 16, vuosikurssiId: 2, ryhmaId: 3, opiskelijanumero: "2006", etunimi: "Sari", sukunimi: "Koski", rooli: "opiskelija" },
  { id: 17, vuosikurssiId: 2, ryhmaId: 3, opiskelijanumero: "2007", etunimi: "Petri", sukunimi: "Niemi", rooli: "opiskelija" },
  { id: 18, vuosikurssiId: 2, ryhmaId: 3, opiskelijanumero: "2008", etunimi: "Anu", sukunimi: "Lehtonen", rooli: "opiskelija" },
  { id: 19, vuosikurssiId: 2, ryhmaId: 1, opiskelijanumero: "2009", etunimi: "Janne", sukunimi: "Salmi", rooli: "opiskelija" },
  { id: 20, vuosikurssiId: 2, ryhmaId: 2, opiskelijanumero: "2010", etunimi: "Tiina", sukunimi: "Koskinen", rooli: "opiskelija" },
];